HOSTS:
  centos-6-puppet:
    platform: centos-6-x64
    image: pauldavidgilligan/docker-centos6-puppet-ruby215
    hypervisor: docker
    docker_preserve_image: true
CONFIG: 
  log_level: verbose
  type: foss